# Generated by Django 6.0.1 on 2026-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('departamento', models.TextField(blank=True, max_length=50, null=True)),
                ('fecha_contratacion', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
